---
layout: post
title: django或者python中的包路径问题
tags:
- django
- path
- python
status: publish
type: post
published: true
meta:
  _edit_last: '1'
  views: '167'
---
今天因为修改了源代码，所以需要重启django的fastcgi进程，kill之后，运行命令，确提示：Error: Could not import settings 'aituans.settings' (Is it on sys.path?): No module named settings

找不到settings，可是我的settings.py明明存在，而且没有动过，应该不会出问题；然后就想到可能是路径问题，仔细一看目录，在主目录/home/www/aituans下还有一个aituans文件夹，难道因为重名，导致python无法解析到settings.py？

kill掉aituans/aituans/下正在运行的进程，然后给文件夹改名，然后再启动django的进程，OK了。

&nbsp;

特此记录下
